### ISSUE TITLE
Cannot add new visit to Hospital Application

### ISSUE THREAD

**Issue by aasam028** [uoForms/quickforms3#14]
Server Times out when trying to add new visit. 
On Sami's local PC , he was able to fix this by setting the auto increment property on the Referral Table in SQL.

**Comment by aasam028** [comment]
Error Message after debugging. The Auto increment property was already fixed on the Hospital application.

![hospital app error](https://cloud.githubusercontent.com/assets/15662347/16021547/4f38ddb4-3181-11e6-9e63-3b5119179f66.PNG)
![hospital 2](https://cloud.githubusercontent.com/assets/15662347/16021554/5411bb62-3181-11e6-80b0-3c5acf7219e7.PNG)

**Comment by tarimshahab** [comment]
If `$` is undefined, then you are probably not including jQuery properly. Are your script tags set properly?
