### ISSUE TITLE
Adding zip file of app (pregapp, francine) to BUILDS-Dev

### ISSUE THREAD

**Issue by katchengli** [uoForms/quickforms3#2]
@beneze

**Comment by beneze** [comment]
Thanks. I noticed that the server has only 4G in the C. It may run out of disk space any time soon. Any plans to mitigate this?  Ben Eze

**Comment by katchengli** [comment]
Hi Ben good catch. We'll need to change the database management plan. Can you do this? If you look in Dropbox, you can see the document for the backup of the database of the EBC course quickForms\EBC6230 Course\TA files\Riyas_BPM_Installation_Documentation

We can inspire ourselves from the one used for the course... You should be able to see in the Server Master List where the DB is (I think it's simply on the server for the course.)

There's already an existing db management maintenance plan for this server/database but I think it's not deleting older files.

Let me know if you need help.

**Comment by beneze** [comment]
Ok. I will look into that today. Maybe there are some databases that we should remove the daily backups as well. I mean those that are not actively changing at this point. What is the policy for deleting old files - how long should they be kept?  Ben Eze

**Comment by katchengli** [comment]
There's only two databases that are being backed up. RPP and Pregapp, I think. Not sure what the policy is... Maybe send a quick email to Prof. Peyton... Keeping one week should be more enough, but I'm not sure.

**Comment by beneze** [comment]
I don't think this is necessary. I was able to do some cleanup and now we have about 8 G of free space. This is good enough for now. I have also started pushing backups for francine to BUILDS-DEV
