### ISSUE TITLE
Correct sorting in the CWS reports

### ISSUE THREAD

**Issue by mgarzon** [uoForms/quickforms3#58]
Scores are grouped by sub-domain, although in the wrong order (should be in the ICF order rather than alphabetical order). 

Sort sub-domains by ICF number (provided on excel spreadsheet) rather than alphabetically.Table [dbo].[lkup_evaluation] has a column evaluationOrder that could be used for this purpose. 

Sort functional scores in reverse chronological order within each sub-domain grouping (i.e. the most recent score on top).

Remove the ability to sort on care provider and assessment date headings.

**Comment by pmata100** [comment]
Done. Next step: testing
